#!/usr/bin/env python3
"""Regenerate the pinned wheel lists the Flatpak build installs.

flatpak-builder runs offline, so every wheel has to be named in the manifest
with its hash. This asks pip to resolve the same dependencies pyproject.toml
declares, for the Python and architecture the Flatpak runtime provides, and
writes the two module files the manifest includes.

Run it after changing dependencies in pyproject.toml, or when the runtime moves
to a new Python version:

    python scripts/flatpak_gen_deps.py

PySide6 is swapped for PySide6-Essentials: the app only imports QtCore, QtGui,
QtNetwork, QtSvg and QtWidgets, so the Addons half of PySide6 would add a few
hundred megabytes to the bundle for nothing.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FLATPAK_DIR = ROOT / "packaging" / "flatpak"

# Wheels are resolved for every Python the runtime might carry, and pip picks
# the matching one at build time from the local find-links directory. Listing
# more than one keeps the manifest working when the runtime moves to a new
# Python instead of failing the build with no compatible wheel.
PYTHON_VERSIONS = (("3.12", "cp312"), ("3.13", "cp313"))
PLATFORMS = ("manylinux_2_28_x86_64", "manylinux2014_x86_64", "manylinux_2_17_x86_64")

# Installing the app itself from source needs its build backend on hand.
BUILD_BACKEND = ("hatchling", "hatch-vcs")

_PIP_INSTALL = (
    'pip3 install --no-index --find-links="file://${PWD}" '
    "--prefix=${FLATPAK_DEST} --no-build-isolation"
)


def runtime_requirements() -> list[str]:
    """The app's dependencies, with PySide6 narrowed to Essentials."""
    with (ROOT / "pyproject.toml").open("rb") as fh:
        deps = tomllib.load(fh)["project"]["dependencies"]
    out = []
    for dep in deps:
        spec = dep.split("#", 1)[0].strip()
        if spec.lower().startswith("pyside6"):
            spec = "PySide6-Essentials" + spec[len("PySide6") :]
        out.append(spec)
    return out


def resolve(requirements: list[str]) -> list[tuple[str, str, str, str]]:
    """Ask pip which wheels satisfy *requirements*, for every supported Python."""
    merged: dict[str, tuple[str, str, str, str]] = {}
    for python_version, abi in PYTHON_VERSIONS:
        for row in _resolve_one(requirements, python_version, abi):
            merged[row[2]] = row  # keyed by URL, so shared wheels appear once
    return sorted(merged.values(), key=lambda row: (row[0].lower(), row[2]))


def _resolve_one(
    requirements: list[str], python_version: str, abi: str
) -> list[tuple[str, str, str, str]]:
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "report.json"
        cmd = [
            sys.executable, "-m", "pip", "install",
            "--dry-run", "--quiet", "--only-binary", ":all:",
            "--target", str(Path(tmp) / "unused"),
            "--report", str(report),
            "--python-version", python_version,
            "--implementation", "cp",
            "--abi", abi,
        ]
        for platform in PLATFORMS:
            cmd += ["--platform", platform]
        cmd += requirements
        subprocess.run(cmd, check=True)
        data = json.loads(report.read_text())

    found = []
    for item in data["install"]:
        info = item["download_info"]
        found.append(
            (
                item["metadata"]["name"],
                item["metadata"]["version"],
                info["url"],
                info["archive_info"]["hashes"]["sha256"],
            )
        )
    return sorted(found, key=lambda row: row[0].lower())


def render(name: str, note: str, wheels: list[tuple[str, str, str, str]]) -> str:
    packages = " ".join(sorted({row[0] for row in wheels}))
    lines = [
        "# Generated by scripts/flatpak_gen_deps.py. Do not edit by hand.",
        f"# {note}",
        f"# {len(wheels)} wheels, covering Python "
        f"{' and '.join(v for v, _ in PYTHON_VERSIONS)}.",
        f"name: {name}",
        "buildsystem: simple",
        "build-commands:",
        f"  - {_PIP_INSTALL} {packages}",
        "sources:",
    ]
    for pkg, version, url, sha256 in wheels:
        lines += [
            f"  # {pkg} {version}",
            "  - type: file",
            f"    url: {url}",
            f"    sha256: {sha256}",
        ]
    return "\n".join(lines) + "\n"


def main() -> None:
    FLATPAK_DIR.mkdir(parents=True, exist_ok=True)

    runtime = resolve(runtime_requirements())
    names = {row[0].lower() for row in runtime}
    backend = [row for row in resolve(list(BUILD_BACKEND)) if row[0].lower() not in names]

    targets = {
        "python3-deps.yaml": render(
            "python3-deps",
            "Runtime dependencies, from the project dependencies in pyproject.toml.",
            runtime,
        ),
        "python3-build-backend.yaml": render(
            "python3-build-backend",
            "Build backend, needed to install the app itself from source offline.",
            backend,
        ),
    }
    for filename, text in targets.items():
        (FLATPAK_DIR / filename).write_text(text)
        print(f"wrote packaging/flatpak/{filename}")

    abi_bound = {
        r[0] for r in runtime + backend if "abi3" not in r[2] and "-none-any" not in r[2]
    }
    print(f"{len(runtime)} runtime wheels, {len(backend)} build wheels")
    print(f"shipped per Python version: {', '.join(sorted(abi_bound))}")


if __name__ == "__main__":
    main()
